### PR TITLE
Create appveyor.yml

### PR DESCRIPTION
**Pull request by jwscook**

### CODE REVIEW

**Comment by jwscook** [comment]
Asking on Appveyor.jl https://github.com/JuliaCI/Appveyor.jl/issues/25

**Comment by jwscook** [comment]
I think that's enough of that.

**Comment by richardreeve** [comment]
@jwscook Maddening. I'm sure you tried this, but I was just wondering whether not installing it using pip was something you had tried to do? I don't understand conda, python or pip, but can you just install it using some julia version of the `conda install -c scottishcovidresponse data-pipeline-api` option that is suggested in the repo as an alternative? I'm sure you tried it, but it might avoid having to install pip at all...

**Comment by jwscook** [comment]
The thing I've learnt from this is not to use Windows.

**Comment by richardreeve** [comment]
Yes, that seems sensible to me as a conclusion! I've happily never used Windows, and I never intend to (HPUX / SunOS -> Solaris -> Linux -> OSX -> Linux / macOS). Thanks for trying anyway...

**Pull request closed without merging**
